# Generated by Django 5.0.6 on 2024-06-21 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credit_line', '0003_alter_creditlineadjustment_previous_end_date'),
        ('credit_origination', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditSubline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subline_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_disbursed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=3, max_digits=6)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive')], default='pending', max_length=25)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('credit_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit_line.creditline')),
                ('subline_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='credit_origination.credittype')),
            ],
        ),
    ]
