# Generated by Django 5.0.6 on 2024-06-25 16:25

import credit_line.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_subline', '0003_interestrateadjustment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditSublineStatusAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive')], max_length=25)),
                ('adjusted_status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive')], max_length=25)),
                ('effective_date', models.DateField(default=credit_line.models.current_date)),
                ('reason_for_adjustment', models.TextField()),
                ('adjustment_status', models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('implemented', 'Implemented')], default='pending_review', max_length=20)),
                ('credit_subline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subline_status_adjustments', to='credit_subline.creditsubline')),
            ],
            options={
                'ordering': ['-effective_date'],
            },
        ),
    ]
