# Generated by Django 5.0.6 on 2024-06-18 18:34

import credit_line.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_line', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditLineAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_credit_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('previous_end_date', models.DateField()),
                ('new_end_date', models.DateField(blank=True, null=True)),
                ('previous_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=25)),
                ('new_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=25, null=True)),
                ('previous_currency', models.CharField(choices=[('mxn', 'MXN')], max_length=5)),
                ('new_currency', models.CharField(blank=True, choices=[('mxn', 'MXN')], max_length=5, null=True)),
                ('adjustment_date', models.DateField(default=credit_line.models.current_date)),
                ('adjustment_status', models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('implemented', 'Implemented')], default='pending_review', max_length=20)),
                ('reason', models.TextField()),
                ('credit_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='credit_line.creditline')),
            ],
            options={
                'ordering': ['-adjustment_date'],
            },
        ),
    ]
