# Generated by Django 5.0.6 on 2024-06-19 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_line', '0002_creditlineadjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditlineadjustment',
            name='previous_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
