# Generated by Django 5.0.6 on 2024-06-26 19:19

import credit_line.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credit_subline', '0004_creditsublinestatusadjustment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_length', models.PositiveIntegerField()),
                ('repayment_frequency', models.CharField(choices=[('biweekly', 'Biweekly'), ('monthly', 'Monthly'), ('bimonthly', 'Bimonthly'), ('quarterly', 'Quarterly')], max_length=10)),
                ('payment_due_day', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(default=credit_line.models.current_date)),
                ('credit_subline', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='credit_subline.creditsubline')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
