# Generated by Django 5.0.6 on 2024-06-27 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('principal_component', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_component', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('delayed', 'Delayed')], default='pending', max_length=10)),
                ('actual_payment_date', models.DateField(blank=True, null=True)),
                ('loan_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='loan_management.loanterm')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
