name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create media and static directories
        run: |
          mkdir -p media
          mkdir -p static
          chmod -R 777 media
          chmod -R 777 static

      - name: Set up .env file
        run: |
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          # echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          # echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          # echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          # echo "DB_PASS=${{ secrets.DB_PASS }}" >> .env
          # Add other environment variables as needed

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"

      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
